CREATE DATABASE IF NOT EXISTS enquete_db;

USE bd_enquete;

CREATE TABLE votos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL, 
    data_voto TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE respostas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voto_id INT,
    resposta VARCHAR(255),
    FOREIGN KEY (voto_id) REFERENCES votos(id) ON DELETE CASCADE
);